App\Entity\Autorizacao\Regra:
    type: entity
    table: autorizacao.regra
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nome:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        ativo:
            type: boolean
            nullable: false
            options:
                default: true
    manyToMany:
        idUsuarios:
            targetEntity: App\Entity\Autorizacao\Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: idRegras
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
