App\Entity\Autorizacao\Aplicacao:
    type: entity
    table: autorizacao.aplicacao
    uniqueConstraints:
        aplicacao_apy_key_unique:
            columns:
                - api_key
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nome:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        apelido:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
        ativo:
            type: boolean
            nullable: false
            options:
                default: true
        dataCadastro:
            type: datetime
            nullable: false
            options:
                default: now()
            column: data_cadastro
        apiKey:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: api_key
    lifecycleCallbacks: {  }
