App\Entity\Autorizacao\Usuario:
    type: entity
    table: autorizacao.usuario
    uniqueConstraints:
        usuarios_unique:
            columns:
                - username
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nome:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        username:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        salt:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        ativo:
            type: boolean
            nullable: false
            options:
                default: true
        dataCadastro:
            type: datetime
            nullable: false
            options:
                default: now()
            column: data_cadastro
    manyToMany:
        idRegras:
            targetEntity: App\Entity\Autorizacao\Regra
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: idUsuarios
            joinTable:
                name: autorizacao.usuario_regra
                joinColumns:
                    -
                        name: id_usuarios
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: id_regras
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
