parameters:
    cors:
        allowed_origin:
            - 'dionysiotonial.local.com'
            - 'teste.local.br'
            - 'http://localhost:3000'
        allowed_headers:
            - AccessToken
            - Content-Type
            - AuthVersion
            - ApiKey
            - Cookie
            - Accept
            - Origin
            - Authorization
    